<?php

namespace Admin\UserBundle\Entity;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getDelegue(){
        $qb = $this->createQueryBuilder('a');
        $qb->select('u')
            ->from('AdminUserBundle:User', 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"ROLE_DELEGUE"%');

        return $qb->getQuery()->getResult();
    }

    public function getSecretaire(){
        $qb = $this->createQueryBuilder('a');
        $qb->select('u')
            ->from('AdminUserBundle:User', 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"ROLE_SECRETAIRE"%');

        return $qb->getQuery()->getResult();
    }


    public function getOnlyDelegue(){
        $qb = $this->createQueryBuilder('a');
        $qb->select('u')
            ->from('AdminUserBundle:User', 'u')
            ->where('u.roles LIKE :roles')
            ->setParameter('roles', '%"ROLE_DELEGUE"%');

        return $qb;
    }

}
