<?php

namespace Admin\TestBundle\Entity;

/**
 * Depense_BudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Depense_BudgetRepository extends \Doctrine\ORM\EntityRepository
{
}
