<?php

namespace Admin\TestBundle\Entity;

/**
 * DepenceBudgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepenceBudgetRepository extends \Doctrine\ORM\EntityRepository
{
}
