<?php

namespace Admin\TestBundle\Entity;

/**
 * DetailCmdRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetailCmdRepository extends \Doctrine\ORM\EntityRepository
{
}
