<?php

namespace Admin\TestBundle\Entity;

/**
 * GroupeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
