<?php

namespace Admin\TestBundle\Entity;

/**
 * Type_ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_ClientRepository extends \Doctrine\ORM\EntityRepository
{
}
